name: Update Organization Members
on:
  schedule:
    - cron: '0 0 * * *' # Updates every night
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  update-members:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Organization Members
        uses: jamesgeorge007/github-organization-members@v1.1.0
        with:
          org: 'Codefied-CodePix'
          token: ${{ secrets.ORG_MEMBER_TOKEN }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          git commit -m "docs: update team member icons" || exit 0
          git push
